service: scheduler-poc

functions: ${file(./resources/functions.yml)}

provider:
  name: aws
  region: "eu-central-1"
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: ${self:custom.config.table_arn}*
        - Effect: "Allow"
          Action:
            - "sqs:*"
          Resource: ${self:custom.config.queue_arn}

custom:
  webpack:
    packager: yarn
    webpackConfig: webpack.config.ts
    includeModules:
      forceExclude:
        - aws-sdk
  config: ${file(./config.json)}

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
